project:
  type: website

website:
  title: "Quarto Trials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - notes.qmd
      - Session4.ipynb
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



